### ISSUE TITLE
你好，编译sillyGirl寻求帮助

### ISSUE THREAD

**Issue by 84896150** [mzzsfy/sillyGirl_qinglong#1]
你好，我用了你的docker镜像部署的sillyGirl，很棒。我想自己编译一个，但是缺少好多库。
github.com/cdle/cable.git
github.com/cdle/boltdb.git
github.com/cdle/qinglong.git
github.com/ufuckee/jd_cookie.git
请问你有这些库的备份文件吗？谢谢

**Comment by mzzsfy** [comment]
这些库已不兼容,请使用作者编译版
